---
driver:
  name: vagrant
  box: base

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      recipe[ubuntu-service-cookbook]
    attributes:
