name             'ubuntu-service'
maintainer       'Mike Berman'
description      'Installs/Configures ubuntu-service-cookbook'
long_description 'Installs/Configures ubuntu-service-cookbook'
version          '0.1.0'
